### ISSUE TITLE
Polymorph interfaces

### ISSUE THREAD

**Issue by derolf** [Eywek/typoa#13]
Consider 

```TypeScript
interface Foo {
  foo: number;
}
interface Bar extends Foo {
  bar: number;
}
```

Currently, `Bar` generates a "flat" representation. However, we should embed `Foo` using `allOf` into `Bar`.

Happy to work on a PR if you agree!

**Comment by Eywek** [comment]
Hello,

Yes, you can try to open a PR if you want

**Comment by derolf** [comment]
Working on it already, do you know how to use ts-morph to only get the own props of a node?

BTW. I think that ONLY interface should generate explicit schema object, all other types should always be inlined.

Otherwise, you get a bunch of weird intermediate explicit schema types in the schema, like this: 

```
        Patched__title-string--__:
            type: object
            properties:
                title:
                    type: string
```

which stems from `Patched<{title: string}>` with 

```
export type Patched<T> = {
  [P in keyof T]?: T[P] extends Array<infer U> ? Array<Patched<U>> : T[P] extends ReadonlyArray<infer U> ? ReadonlyArray<Patched<U>> : Patched<T[P]>;
};
```
