### ISSUE TITLE
bug: typing specific keys in record result in only the keys in the object properties

### ISSUE THREAD

**Issue by vmarchaud** [Eywek/typoa#14]
```
type meta = {
    'email-token'?: string
    'esp'?: string
    [key: string]: string | undefined
}
```

result in:
```
Partial_Pick_Company.meta__:
            type: object
            properties:
                meta:
                    type: object
                    properties:
                        email-token:
                            type: string
                        esp:
                            type: string
```

instead it should type specific keys and also accept any other keys
