### ISSUE TITLE
bug: pattern on arrays

### ISSUE THREAD

**Issue by Eywek** [Eywek/typoa#5]
```ts
      /**
       * @pattern ^[0-9a-fA-F]{24}$
       */
      resourceGroupIds: string[],
```

```yaml
type: object
	properties: {resourceGroupIds: {type: array, items: {type: string}}}
    required: [resourceGroupIds]
```

**Comment by xseman** [comment]
It seems to be resolved.

```ts
interface LoginReq {
	/**
	 * @pattern ^[0-9a-fA-F]{24}$
	 */
	email: string[];
	password: string;
}
```

```yaml
LoginReq:
    type: object
    properties:
        email:
            type: array
            items:
                type: string
            pattern: '^[0-9a-fA-F]{24}$'
        password:
            type: string
    required:
        - email
        - password
```
